dist: xenial
language: python

cache: pip

addons:
  postgresql: "9.6"

stages:
  - name: linting
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: linting
      python: 3.6
      env: TOXENV=pre_commit
    - stage: linting
      python: 3.6
      env: TOXENV=check_readme
    - stage: test
      python: 2.7
      env: ODOO="8.0"
    - stage: test
      python: 2.7
      env: ODOO="9.0"
    - stage: test
      python: 2.7
      env: ODOO="10.0"
    - stage: test
      python: 3.5
      env: ODOO="11.0"
    - stage: test
      python: 3.5
      env: ODOO="12.0"
    - stage: test
      python: 3.6
      env: ODOO="12.0"
    - stage: test
      python: 3.7
      env: ODOO="12.0"
    - stage: test
      python: 3.6
      env: ODOO="13.0"
    - stage: test
      python: 3.8-dev
      env: ODOO="12.0"
    - stage: test
      python: 3.7
      env: ODOO="master"
    - stage: deploy
      script: echo "Deploy to PyPi"
      deploy:
        provider: pypi
        user: acsbidoul
        password:
          secure: ""
        distributions: "sdist bdist_wheel"
        skip_upload_docs: true
        on:
          repo: akretion/odoo-elasticapm
          branch: master
          tags: true
  allow_failures:
    - python: 3.8-dev
    - env: ODOO="master"

install:
  - pip install tox-travis
  - pip install codecov

script:
  - tox

after_success:
  - codecov
